Finalproject/Models/SubCategory.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Finalproject.Models
{
    public class SubCategory
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(250)]
        public string Image { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }

        [MaxLength(50)]
        public string Title { get; set; }

        [MaxLength(50)]
        public string Name { get; set; }

        [ForeignKey("Category")]
        public int CategoryId { get; set; }
        public Category Category{ get; set; }

        public List<Product> Products { get; set; }






    }
}

Finalproject/Areas/admin/Controllers/SubCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Finalproject.Data;
using Finalproject.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Finalproject.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Finalproject.Areas.admin.Controllers
{
    [Area("admin")]
    [Authorize]
    public class SubCategoriesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public SubCategoriesController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }


        // GET: admin/SubCategories
        public async Task<IActionResult> Index(int page = 1, double itemCount = 10)
        {

            VmHome model = new VmHome()
            {

                Products = _context.Products.ToList(),

            };

            List<SubCategory> subCategories = _context.SubCategories.OrderByDescending(m => m.Id).ToList();
            model.PageCount = (int)Math.Ceiling(subCategories.Count / itemCount);
            model.SubCategories = subCategories.Skip((page - 1) * (int)itemCount).Take((int)itemCount).ToList();
            model.Page = page;
            model.ItemCount = itemCount;

            return View(model);

            var appDbContext = _context.SubCategories.OrderByDescending(m => m.Id).Include(s => s.Category);
            return View(await appDbContext.ToListAsync());
        }

        // GET: admin/SubCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subCategory = await _context.SubCategories
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subCategory == null)
            {
                return NotFound();
            }

            return View(subCategory);
        }

        // GET: admin/SubCategories/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        // POST: admin/SubCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( SubCategory subCategory)
        {
            if (ModelState.IsValid)
            {
                if (subCategory.ImageFile != null)
                {
                    if (subCategory.ImageFile.ContentType == "image/jpeg" || subCategory.ImageFile.ContentType == "image/png")
                    {
                        if (subCategory.ImageFile.Length <= 3000000)
                        {
                            string FileName = Guid.NewGuid() + "-" + subCategory.ImageFile.FileName;
                            string FilePath = Path.Combine(_webHostEnvironment.WebRootPath, "UploadsSubcategory", FileName);
                            using (var stream = new FileStream(FilePath, FileMode.Create))
                            {
                                subCategory.ImageFile.CopyTo(stream);
                            }
                            subCategory.Image = FileName;
                            _context.SubCategories.Add(subCategory);
                            await _context.SaveChangesAsync();
                            return RedirectToAction(nameof(Index));

                        }
                        else
                        {
                            ModelState.AddModelError("", "you can choose only 3 mb image file");
                            return View(subCategory);
                        }


                    }
                    else
                    {
                        ModelState.AddModelError("", "you can choose only image file");
                        return View(subCategory);

                    }

                }
                else
                {
                    ModelState.AddModelError("", " choose image file");
                    return View(subCategory);

                }


            }
            return View(subCategory);
        }

        // GET: admin/SubCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subCategory = await _context.SubCategories.FindAsync(id);
            if (subCategory == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", subCategory.CategoryId);
            return View(subCategory);
        }

        // POST: admin/SubCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SubCategory subCategory)
        {
            if (ModelState.IsValid)
            {
                if (subCategory.ImageFile != null)
                {
                    if (subCategory.ImageFile.ContentType == "image/jpeg" || subCategory.ImageFile.ContentType == "image/png")
                    {
                        if (subCategory.ImageFile.Length <= 3000000)
                        {
                            string olddata = Path.Combine(_webHostEnvironment.WebRootPath, "UploadsSubcategory", subCategory.Image);
                            if (System.IO.File.Exists(olddata))
                            {
                                System.IO.File.Delete(olddata);
                            }
                            string FileName = Guid.NewGuid() + "-" + subCategory.ImageFile.FileName;
                            string FilePath = Path.Combine(_webHostEnvironment.WebRootPath, "UploadsSubcategory", FileName);
                            using (var stream = new FileStream(FilePath, FileMode.Create))
                            {
                                subCategory.ImageFile.CopyTo(stream);
                            }
                            subCategory.Image = FileName;
                            _context.SubCategories.Update(subCategory);
                            await _context.SaveChangesAsync();
                            return RedirectToAction(nameof(Index));

                        }
                        else
                        {
                            ModelState.AddModelError("", "you can choose only 3 mb image file");
                            return View(subCategory);
                        }


                    }
                    else
                    {
                        ModelState.AddModelError("", "you can choose only image file");
                        return View(subCategory);

                    }

                }
                else
                {
                    ModelState.AddModelError("", " choose image file");
                    return View(subCategory);

                }


            }
            return View(subCategory);
        }

        // GET: admin/SubCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subCategory = await _context.SubCategories
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subCategory == null)
            {
                return NotFound();
            }

            return View(subCategory);
        }

        // POST: admin/SubCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subCategory = await _context.SubCategories.FindAsync(id);
            string olddata = Path.Combine(_webHostEnvironment.WebRootPath, "UploadsSubcategory", subCategory.Image);
            if (System.IO.File.Exists(olddata))
            {
                System.IO.File.Delete(olddata);
            }
            _context.SubCategories.Remove(subCategory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubCategoryExists(int id)
        {
            return _context.SubCategories.Any(e => e.Id == id);
        }
    }
}

Finalproject/Areas/admin/Views/SubCategories/Create.cshtml
@model Finalproject.Models.SubCategory

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>SubCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create"  method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info mt-2" asp-action="Index">Back to List</a>
</div>

Finalproject/Areas/admin/Views/SubCategories/Delete.cshtml
@model Finalproject.Models.SubCategory

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SubCategory</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dt class="col-sm-10">
            <img src="~/UploadsSubcategory/@Model.Image" alt="Alternate Text" style="max-width:500px; max-height:500px" />
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-info" asp-action="Index">Back to List </a>
    </form>
</div>

Finalproject/Areas/admin/Views/SubCategories/Details.cshtml
@model Finalproject.Models.SubCategory

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>SubCategory</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dt class="col-sm-10">
            <img src="~/UploadsSubcategory/@Model.Image" alt="Alternate Text" style="max-width:500px; max-height:500px" />
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

Finalproject/Areas/admin/Views/SubCategories/Edit.cshtml
@model Finalproject.Models.SubCategory

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>SubCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <dt class="col-sm-2">
                <img src="~/UploadsSubcategory/@Model.Image" alt="Alternate Text" style="max-width:500px; max-height:500px" />
            </dt>

            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <input asp-for="@Model.Id" hidden />
            <input asp-for="@Model.Image" hidden />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info mt-2" asp-action="Index">Back to List</a>
</div>

Finalproject/Areas/admin/Views/SubCategories/Index.cshtml
@model VmHome

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h1 class="text-danger">NOTE!:Her Categoryaya gore bir TITLE yazmaq kifayet eder digerlerinin yazilib yazilmamagi sizden asilidir.</h1>

<p>
    <a class="btn btn-success  mt-3" asp-action="Create">Create New</a>
</p>
<table class="table">

    <tbody>
@foreach (var item in Model.SubCategories) {
        <tr>
            <td>
                <img src="~/UploadsSubcategory/@item.Image" alt="Alternate Text" style="max-width:50px; max-height:50px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item @(Model.Page == 1 ? "disabled" : "")">
            <a class="page-link pageItemCount" asp-area="admin" asp-controller="SubCategories" asp-action="index" asp-route-page="@(Model.Page - 1)" asp-route-itemCount="@Model.ItemCount">Previous</a>
        </li>
        @for (int i = 1; i <= Model.PageCount; i++)
        {
<li class="page-item @(Model.Page == i ? "active" : "")" aria-current="page">
    <a class="page-link pageItemCount" asp-area="admin" asp-controller="SubCategories" asp-action="index" asp-route-page="@i" asp-route-itemCount="@Model.ItemCount">@i</a>
</li>
}
        <li class="page-item @(Model.Page == Model.PageCount ? "disabled" : "")">
            <a class="page-link pageItemCount" asp-area="admin" asp-controller="SubCategories" asp-action="index" asp-route-page="@(Model.Page + 1)" asp-route-itemCount="@Model.ItemCount">Next</a>
        </li>
    </ul>
</nav>